name: Privado Code Scan

on: [push]

jobs:
  privado_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login and pull latest Docker image
      run: |
        echo "Login to Docker registry"
        PRIVADO_API_TOKEN=${{ secrets.PRIVADO_API_TOKEN }}
        PRIVADO_API_HOST=${{ secrets.PRIVADO_API_HOST }}
        PRIVADO_API_ID=${{ secrets.PRIVADO_API_ID }}
        TOKEN=$(curl -s -H 'Content-Type: application/json' -H "Authorization: Token $PRIVADO_API_TOKEN" -H "idt: $PRIVADO_API_TOKEN" -H 'data-url: /ce/integrations/customers/${PRIVADO_API_ID}/docker-registry-token' "${PRIVADO_API_HOST}/ce/integrations/customers/${PRIVADO_API_ID}/docker-registry-token?ci=true")
        echo $TOKEN | docker login --username AWS --password-stdin 638117407428.dkr.ecr.eu-west-1.amazonaws.com
        echo "Pulling latest Docker image"
        docker pull 638117407428.dkr.ecr.eu-west-1.amazonaws.com/scanner-agent:latest
      shell: bash

    - name: Run Privado Scan
      run: |
        # Export environment variables to a file
        echo "PRIVADO_API_TOKEN=${{ secrets.PRIVADO_API_TOKEN }}" > $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_API_ID=${{ secrets.PRIVADO_API_ID }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_API_HOST=${{ secrets.PRIVADO_API_HOST }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_BASE_PATH=$PRIVADO_BASE_PATH" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_CI_PLATFORM=CUSTOM" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_REPOSITORY_ID=${{ github.repository_id }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_REPOSITORY_NAME=${{ github.repository }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_COMMIT_ID=${{ github.sha }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_DEFAULT_BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_WORKSPACE/.privado.env
        echo "PRIVADO_REPOSITORY_URL=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_WORKSPACE/.privado.env
        # Run Docker container with environment variables
        docker run -t -v $GITHUB_WORKSPACE:/privado \
          --env-file $GITHUB_WORKSPACE/.privado.env --privileged \
          638117407428.dkr.ecr.eu-west-1.amazonaws.com/scanner-agent:latest
