name: Privado Code Scan

on: [push]

jobs:
  privado_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Download Privado CLI
      run: |
        curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash

    - name: Scan with Privado
      run: |
        privado scan .

    - name: Display Results
      run: |
        cat .privado/privado.json
